export type UPDATE_GREETING = "UPDATE_GREETING";
export type INCREMENT = "INCREMENT";
export type EDIT = "EDIT";

export const UPDATE_GREETING: UPDATE_GREETING = "UPDATE_GREETING";
export const INCREMENT: INCREMENT = "INCREMENT";
export const EDIT: EDIT = "EDIT";
